name: DockerImageCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

      
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "galinakaz/app-dima:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "galinakaz/app-dima:$GITHUB_SHA"
    

